#!/bin/sh

# ----------------------------------------------------------------------
#  $Id$
#
#  Reports Openbox specific x-properties
# ----------------------------------------------------------------------

WIN_ID="$(xprop -root _NET_ACTIVE_WINDOW | awk '{print $NF}')"

xterm -title "Window's properties (obxprop)" -e "obxprop --id $WIN_ID | grep "^_OB" | ${PAGER}"
