#!/bin/sh

# ----------------------------------------------------------------------
#  $Id$
#
#  Reports current window's X properties
# ----------------------------------------------------------------------

WIN_ID="$(xprop -root _NET_ACTIVE_WINDOW |
        cut -d"," -f1 |
        awk '{print $NF}')"

xterm -title "Window's properties" \
    -e "xprop -notype -id $WIN_ID | ${PAGER}"
