#!/bin/sh

# ----------------------------------------------------------------------
#  $Id$
#
#  Automatic MOUNTer for OpenBSD
# ----------------------------------------------------------------------

# ----------------------------------------------------------------------------
# Copyright 2015-2020 Alessandro De Laurenzis
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# 1. Redistributions of source code must retain the above copyright notice,
# this list of conditions and the following disclaimer.
#
# 2. Redistributions in binary form must reproduce the above copyright notice,
# this list of conditions and the following disclaimer in the documentation
# and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
# LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
# CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.
# ----------------------------------------------------------------------------

_help() { less << __HELP__
NAME
  amount - Automatic MOUNTer

SYNOPSIS
  amount -h
  amount [-k] [-r dir] [-g group] [-m mode] [-o opt] [-e device ...]

DESCRIPTION
  amount is an OpenBSD specific, POSIX compliant shell script to manage
  removable devices; it presents a list of available partitions, and
  (un)mount them upon user request. Optionally, it opens a filemanager
  window after mount operations.
  A few commands used by amount require special permissions (disklabel(8),
  {u,}mount(8), fsck(8), ...), so it should be run through doas(1).

  The following options are available:

  -k           Keep error messages until a key is pressed

  -r dir       Mount root dir; it must exist and have the proper
               permissions (defaults to /vol);

  -g group     Mount dir will be owned by this group;

  -m mode      Mount dir will have these permissions;

  -o opt       Mount options (defaults to rw,nodev,nosuid,noatime);

  -e device    Do not manage this device.

AUTHOR
  Alessandro De Laurenzis, <just22@atlantide.mooo.com>
__HELP__
}

# ----------------------------------------------------------------------
# Defaults
#
mroot=/vol
mgroup=diskmount
mmode=0775
mopt=rw,nodev,nosuid,noatime
exdev=

# ----------------------------------------------------------------------
# Helpers
#
gsub() {
        s="$1"; p="$2"; v="$3"
        while [ "${s#*$p}" != "$s" ]; do
                s="${s%%$p*}$v${s#*$p}"
        done
        echo "$s"
}

err() {
        if [ "$1" == -r ]; then
                rm -r "$mdir"
                shift
        fi
        [ -n "$1" ] && echo "amount: $1"
        if [ -n "${keep+set}" ]; then
                stty raw
                dd bs=1 count=1 2>/dev/null
                stty -raw
        fi
        exit 1
}


# ----------------------------------------------------------------------
# Command line argument parsing
#
while getopts ":hkr:g:m:o:e:" arg; do
        case "$arg" in
         k)    keep= ;;
         r)   mroot="$OPTARG" ;;
         g)  mgroup="$OPTARG" ;;
         m)   mmode="$OPTARG" ;;
         o)    mopt="$OPTARG" ;;
         e)   exdev="$OPTARG $exdev" ;;
         h) _help; exit 0 ;;
         :) echo "${0##*/}: Option -$OPTARG requires an argument"; exit 1 ;;
        \?) echo "${0##*/}: Unknown option: -$OPTARG"; exit 1
        esac
done
shift $(($OPTIND - 1))


# ----------------------------------------------------------------------
# Variable description:
#   diskn = Disk name (dev:duid)
#     dev = Device name
#    desc = Disk description
#  diskid = Disk identifier (desc + label)
#   partf = Found (at least) a partition for a certain diskid
#   partn = Partition name
#   partt = Partition type
#  action = Mount/unmount
#

# Redirect stdout to stderr by default, and use >&3 to return mount dir
exec 3>&1 1>&2

actno=0
for diskn in $(gsub $(sysctl -n hw.disknames) "," " "); do
        dev=${diskn%:*}
        [ "${exdev#*$dev}" == "$exdev" ] || continue

        unset partf
        disklabel -h "$dev" 2>/dev/null |&
        while read -p line; do
                case "$line" in
                disk:*)
                        desc="${line#disk:}"
                        ;;
                label:*)
                        diskid="${line#label:}${desc}"
                        diskid="${diskid## }"
                        echo "Disk Id: $diskid ($dev)"
                        ;;
                a:*|d:*|e:*|f:*|g:*|h:*|i:*|j:*|k:*|l:*|m:*|n:*|o:*|p:*)
                        partf=
                        partn=${line%:*}
                        partd="$(echo $line | awk '{print $2}')"
                        partt="$(echo $line | awk '{print $4}')"

                        if [ "$partt" != "unknown" ]; then
                                let ++actno
                                if mount | grep -q "${dev}${partn}"; then
                                        action="Unmount"
                                else
                                        action="  Mount"
                                fi

                                menuitem="$(printf "%2d:" "$actno") $action"
                                menuitem="$menuitem ${dev}${partn} $partt $partd"
                                echo "$menuitem"
                                set -- "$@" "$menuitem"
                        fi
                        ;;
                esac
        done
        [ -n "${partf+set}" ] && echo
done

if [ $# -eq 0 ]; then
        err "No devices or insufficient permissions"
fi

echo -n "Select an action: "; read partsel

[ -z "$partsel" ] && exit 0

read foo action devpart partt foo <<- EOT
        $(eval "echo \${$partsel}")
EOT

mdir="${mroot}/${devpart}"
case "$action" in
 *Mount)
        [ -d "$mdir" ] || mkdir -m "$mmode" -p "$mdir"
        chgrp "$mgroup" "$mdir"
        [ $? -ne 0 ] && err

        case "$partt" in
         4.2BSD) mopt="-t ffs -o $mopt"; run_fsck= ;;
          MSDOS) mopt="-t msdos -o $mopt" ;;
         ext2fs) mopt="-t ext2fs -o $mopt" ;;
            UDF) mopt="-t udf" ;;
        ISO9660) mopt="-t cd9660" ;;
              *) err "Mount of $partt not supported"
        esac

        if [ -n "${run_fsck+set}" ]; then
                [ ! fsck -p -y /dev/"$devpart" ] && err -r
        fi

        mount $mopt /dev/"$devpart" "$mdir"
        [ $? -ne 0 ] && err -r

        # Return the mount dir path
        echo "$mdir" >&3

        ;;

Unmount)
        umount "$mdir"
        [ $? -ne 0 ] && err

        rm -r "$mdir"
        ;;

      *)
        exit 0
esac

