#!/bin/sh

# ----------------------------------------------------------------------
#  $Id$
#
#  catppuccin-init - Shell script to setup catppuccin color themes
# ----------------------------------------------------------------------

[ -e ~/.catppuccin ] || mkdir ~/.catppuccin

cd ~/.catppuccin

# XResources
[ -d ./xresources ] &&
        (cd ./xresources && git pull) ||
        git clone https://github.com/catppuccin/xresources.git

# iTerm
[ -d ./iterm ] &&
        (cd ./iterm && git pull) ||
        git clone https://github.com/catppuccin/iterm.git

# Xfce4-terminal
[ -d ./xfce4-terminal ] &&
        (cd ./xfce4-terminal && git pull) ||
        git clone https://github.com/catppuccin/xfce4-terminal.git

# kitty
[ -d ./kitty ] &&
        (cd ./kitty && git pull) ||
        git clone https://github.com/catppuccin/kitty.git

# tmux
[ -d ./tmux ] &&
        (cd ./tmux && git pull) ||
        git clone https://github.com/catppuccin/tmux.git

# vim
[ -d ./vim ] &&
        (cd ./vim && git pull) ||
        git clone https://github.com/catppuccin/vim.git

# Fzf
[ -d ./fzf ] &&
        (cd ./fzf && git pull) ||
        git clone https://github.com/catppuccin/fzf.git

# Set default colorscheme
catppuccin-frappe

