#!/bin/sh

# ----------------------------------------------------------------------
#  $Id$
#
#   Toggle performance policy
# ----------------------------------------------------------------------

case $(sysctl -n hw.perfpolicy) in
    auto) /usr/bin/doas sysctl hw.perfpolicy=high
          ;;
    high) /usr/bin/doas sysctl hw.perfpolicy=auto
          ;;
    *)
          ;;
esac
