#!/bin/sh

# ----------------------------------------------------------------------
#  $Id$
#
#  Loops among performance policies
# ----------------------------------------------------------------------

case $(sysctl -n hw.perfpolicy) in
    auto) sudo sysctl hw.perfpolicy=high
          ;;
    high) sudo sysctl hw.perfpolicy=auto
          ;;
    *)
          ;;
esac
