#!/bin/sh

# Kill daemon on exit
trap "LOOP=0" HUP INT QUIT ABRT KILL TERM

LOOP=1
while [ "$LOOP" == 1 ]; do
    if [ "$(apm -a)" -eq 0 ]; then
        if [ "$(apm -l)" -le 5 ]; then
            logger -t "check-bat-status" "Critical low battery level: suspending..."
            apm -Z
        elif [ "$(apm -l)" -le 20 ]; then
            (echo "This computer is running on low battery level."; \
             echo "Plug-in the AC adapter or hibernate the system!") | \
            xmessage -title "Low battery" -buttons "Hibernate now":1,"OK":0 -timeout 60 -file -
            [ "$?" -eq 1 ] && apm -Z
        fi
    fi
    # Check every 3 min
    sleep 180
done
