#!/bin/sh

DIM=$(expr \
        $(xrandr -q |
                egrep -o "[0-9]+x[0-9]+\+0\+0" |
                awk -F "x" '{print $1}') \
        - 168)

echo "minimum_size $DIM 13" > /tmp/conkyrc

sed -e "/minimum_size/d; /maximum_size/d" \
        ~/.config/conky/conkyrc-statusline-dock \
        >> /tmp/conkyrc

conky -c /tmp/conkyrc
