#!/bin/sh

# ----------------------------------------------------------------------
#  $Id$
#
#  Simple timer
# ----------------------------------------------------------------------

# No output msgs, please
exec >/dev/null 2>&1

set -A MENU_ITEMS \
        "auto" \
        "high"

POL=$(printf "%s\n" "${MENU_ITEMS[@]}" | dmenu-cust -p PerfPolicy[$(sysctl -n hw.perfpolicy)]: -i "$@")

[ -n "$POL" ] && /usr/bin/doas sysctl hw.perfpolicy="$POL"
