#!/bin/sh

# ----------------------------------------------------------------------
#  $Id$
#
#  dmenu launcher with custom default settings
# ----------------------------------------------------------------------

dmenu -fn "DejaVu Sans Mono:size=9" \
      -nb "#eee8d5" \
      -nf "#293a1a" \
      -sb "#2aa198" \
      -sf "#fdf6e3" \
      $@
