#!/bin/sh

# ----------------------------------------------------------------------
#  $Id$
#
#  Xscreensaver control
# ----------------------------------------------------------------------

# No output msgs, please
exec >/dev/null 2>&1

_array() {
        if [ "$KSH_VERSION" ]; then
                set -A $1 "${@:2}"
        else
                eval $1='("${@:2}")'
        fi
}

_array MENU_ITEMS \
        "Enable" \
        "Disable" \
        "Lock Screen" \
        "Restart" \
        "Settings"

case "$(printf "%s\n" "${MENU_ITEMS[@]}" |
        dmenu-cust -p XScreensaver: -i "$@")" in
Enable)
        xscreensaver
        ;;
Disable)
        xscreensaver-command -exit
        ;;
Lock*)
        xscreensaver-command -lock
        ;;
Restart)
        xscreensaver-command -restart
        ;;
Settings)
        xscreensaver-demo
        ;;
esac
