#!/bin/sh

# ----------------------------------------------------------------------
#  $Id$
#
#  Wrapper around dmanu (it sets default font and colors)
# ----------------------------------------------------------------------

/usr/bin/env dmenu \
        -m  0 \
        -fn "Terminus-10" \
        -nf "#073642" \
        -nb "#EEE8D5" \
        -sf "#EEE8D5" \
        -sb "#93A1A1" \
        $@
