#!/bin/sh

# ----------------------------------------------------------------------
#  $Id$
#
#  Xscreensaver control
# ----------------------------------------------------------------------

# No output msgs, please
exec >/dev/null 2>&1

MENU_ITEMS="\
Enable\n\
Disable\n\
Lock Screen\n\
Restart\n\
Settings"

case "$(echo -e $MENU_ITEMS | dmenu -p XScreensaver: "$@")" in
Enable)
        xscreensaver
        ;;
Disable)
        xscreensaver-command -exit
        ;;
Lock*)
        xscreensaver-command -lock
        ;;
Restart)
        xscreensaver-command -restart
        ;;
Settings)
        xscreensaver-demo
        ;;
esac
