#!/bin/sh

# ----------------------------------------------------------------------
#  $Id$
#
#  Simple timer
# ----------------------------------------------------------------------

# No output msgs, please
exec >/dev/null 2>&1

_array() {
        if [ "$KSH_VERSION" ]; then
                set -A $1 "${@:2}"
        else
                eval $1='("${@:2}")'
        fi
}

_array MENU_ITEMS \
        "5min" \
        "10min" \
        "15min" \
        "20min" \
        "25min" \
        "30min" \
        "45min" \
        "60min"

timer -t "+ $(printf "%s\n" "${MENU_ITEMS[@]}" | dmenu-cust -p Timer: "$@")"
