#!/bin/sh

# ----------------------------------------------------------------------
#  $Id$
#
#  Select browser using dmenu
# ----------------------------------------------------------------------

_array() {
        if [ "$KSH_VERSION" ]; then
                set -A $1 "${@:2}"
        else
                eval $1='("${@:2}")'
        fi
}

_array MENU_ITEMS \
        "firefox" \
        "chrome" \
        "surf-launcher"

printf "%s\n" "${MENU_ITEMS[@]}" |
        dmenu-cust -p "Network browser:" "$@" | ${SHELL:-/bin/sh}
