#!/bin/sh

# ----------------------------------------------------------------------
#  $Id$
#
#  Logout from current session (or suspend/reboot/poweroff the machine)
#  using dmenu
# ----------------------------------------------------------------------

# No output msgs, please
exec >/dev/null 2>&1

_array() {
        case "$SH_VERSION" in
        *KSH*)
                a="$1"; shift
                set -A "$a" "$@"
                ;;
        *)
                eval $1='("${@:2}")'
        esac
}

_array MENU_ITEMS \
        "Logout" \
        "Suspend" \
        "Hibernate" \
        "Reboot" \
        "Poweroff"

case "$(printf "%s\n" "${MENU_ITEMS[@]}" |
        dmenu-cust -p "Exit Session:" "$@")" in
Logout)
        if pgrep -x dwm; then
                pkill -x dwm
        elif pgrep -x fluxbox; then
                pkill -P "$(cat /tmp/dbar.pid)"
                rm /tmp/dbar.pid
                fluxbox-remote Exit
        elif pgrep -x cwm; then
                pkill -P "$(cat /tmp/dbar.pid)"
                rm /tmp/dbar.pid
                pkill -x cwm
        elif pgrep -x xfwm4; then
                xfce4-session-logout --logout --fast
        elif pgrep -x openbox; then
                openbox --exit
        else
                pkill -x twm
        fi
        ;;
Suspend)
        /usr/sbin/zzz
        ;;
Hibernate)
        /usr/sbin/ZZZ
        ;;
Reboot)
        /usr/bin/doas /sbin/reboot
        ;;
Poweroff)
        /usr/bin/doas /sbin/shutdown -p now
        ;;
esac

