#!/bin/sh

# ----------------------------------------------------------------------
#  $Id$
#
#  Simple screen capture helper
# ----------------------------------------------------------------------

# No output msgs, please
exec >/dev/null 2>&1

MENU_ITEMS="\
Whole Desktop\n\
Selected Window/Area"

[ "$(echo $MENU_ITEMS |
     dmenu-cust -p Screenshot: -i "$@")" == "Whole Desktop" ] && ARG="desktop"

screenshot $ARG
