#!/bin/sh

# ----------------------------------------------------------------------
#  $Id$
#
#  Simple launch bar usign dmenu
# ----------------------------------------------------------------------

# No output msgs, please
exec >/dev/null 2>&1

_array() {
        case "$SH_VERSION" in
        *KSH*)
                a="$1"; shift
                set -A "$a" "$@"
                ;;
        *)
                eval $1='("${@:2}")'
        esac
}

_array MENU_ITEMS \
        "Term" \
        "FileManager" \
        "Browser" \
        "Email" \
        "Editor" \
        "Removables" \
        "Play" \
        "Display" \
        "Keyboard" \
        "Print" \
        "Timer" \
        "Quit"

sel="$(printf "%s\n" "${MENU_ITEMS[@]}" | dmenu-cust -i -p Menu: "$@")"
case "$sel" in
Term)           x-terminal-emulator ;;
FileManager)    x-filemanager ;;
Browser)        xdg-open http://www.openbsd.org ;;
Email)          x-email-client ;;
Editor)         x-text-editor ;;
Removables)     /usr/bin/doas /usr/local/bin/amount -e sd0 ;;
Play)           play-url -p ;;
Display)        dmenu-xrandr ;;
Keyboard)       dmenu-kbd ;;
Print)          dmenu-lpr ;;
Timer)          dmenu-timer ;;
Quit)           dmenu-session-logout ;;
*)              exit 1 ;;
esac

exit 0
