#!/bin/sh

# ----------------------------------------------------------------------
#  $Id$
#
#  dmenu launcher with custom default settings
# ----------------------------------------------------------------------

NB="#EEE8D5"
NF="#293A1A"
SB="#2AA198"
SF="#FDF6E3"

case "$XSESSION_CMD" in
*xfce*)
        NB="#DCDCDC"
        NF="#404040"
        SB="#404040"
        SF="#DCDCDC"
        ;;
*fluxbox*)
        MONITOR="-m 0"
        ;;
esac

CMD="$(basename ${0%-cust})"

"$CMD" -fn "DejaVu Sans Mono:size=9" \
       -nb "$NB" \
       -nf "$NF" \
       -sb "$SB" \
       -sf "$SF" \
       $MONITOR  \
       "$@"
