#!/bin/sh

# ----------------------------------------------------------------------
#  $Id$
#
#  Simple calculator using tcl-calc and dmenu
# ----------------------------------------------------------------------

__calc()
{
        printf '%s\n' "$result" | xclip -i
        result=$(tcl-calc $(xclip -o |
                dmenu-cust -p Calc: |
                tr -d " ") 2>/dev/null)
}

result=0
while [ -n "$result" ]
do
    __calc
done
