#!/bin/sh

# File:         dmenu-browser
# Purpose:      Select the browser to launch using dmenu
# Author:       A. DE LAURENZIS

set -A MENU_ITEMS \
        "www-x-browser" \
        "chrome" \
        "iridium" \
        "firefox" \
        "surf-launcher"

printf "%s\n" "${MENU_ITEMS[@]}" |
        dmenu -p "Network browser:" "$@" | ${SHELL:-/bin/sh}
