#!/bin/sh

# ----------------------------------------------------------------------
#  $Id$
#
#  dmenu launcher with custom default settings
# ----------------------------------------------------------------------

NB="#EEE8D5"
NF="#293A1A"
SB="#2AA198"
SF="#FDF6E3"

# if pgrep -x fluxbox >/dev/null 2>&1; then
#         MONITOR="-m 0"
# fi

CMD="$(basename ${0%-cust})"

"$CMD" -fn "DejaVu Sans Mono:size=9" \
       -nb "$NB" \
       -nf "$NF" \
       -sb "$SB" \
       -sf "$SF" \
       $MONITOR  \
       "$@"
