#!/bin/sh

# ----------------------------------------------------------------------
#  $Id$
#
#  Simple screen capture helper
# ----------------------------------------------------------------------

# No output msgs, please
exec >/dev/null 2>&1

_array() {
        case "$SH_VERSION" in
        *KSH*)
                a="$1"; shift
                set -A "$a" "$@"
                ;;
        *)
                eval $1='("${@:2}")'
        esac
}

_array MENU_ITEMS \
        "Whole Desktop" \
        "Selected Window/Area"

[ "$(printf "%s\n" "${MENU_ITEMS[@]}" |
     dmenu-cust -p Screenshot: -i "$@")" == "Whole Desktop" ] && ARG="desktop"

screenshot $ARG
