#!/bin/sh

# ----------------------------------------------------------------------
#  $Id$
#
#  Simple timer
# ----------------------------------------------------------------------

# No output msgs, please
exec >/dev/null 2>&1

_array() {
        if [ "$KSH_VERSION" ]; then
                set -A $1 "${@:2}"
        else
                eval $1='("${@:2}")'
        fi
}

_array MENU_ITEMS \
        "us" \
        "it"

setxkbmap "+ $(printf "%s\n" "${MENU_ITEMS[@]}" | dmenu-cust -p Keyboard: "$@")"
