#!/bin/sh

# ----------------------------------------------------------------------
#  $Id$
#
#  Simple timer
# ----------------------------------------------------------------------

# No output msgs, please
exec >/dev/null 2>&1

_array() {
        case "$SH_VERSION" in
        *KSH*)
                a="$1"; shift
                set -A "$a" "$@"
                ;;
        *)
                eval $1='("${@:2}")'
        esac
}

_array MENU_ITEMS \
        "auto" \
        "high"

POL=$(printf "%s\n" "${MENU_ITEMS[@]}" | dmenu-cust -p PerfPolicy[$(sysctl -n hw.perfpolicy)]: -i "$@")

[ -n "$POL" ] && /usr/bin/doas /sbin/sysctl hw.perfpolicy="$POL"
