#!/bin/sh

# ----------------------------------------------------------------------
#  $Id$
#
#  Very basic start menu
# ----------------------------------------------------------------------

menu() {
	local entries="$1"
	local prompt="${2-Run:}"
	sel=$(
		while IFS='' read line; do
			echo "$line" | tr -s "\t" | cut -f 1
		done <<- EOT | dmenu-cust -i -p "$prompt" -l 20
			$entries
		EOT
	)
	[ -z "$sel" ] && return
	while IFS='' read line; do
		[ "${line##"${sel}"}" != "$line" ] && exec ${line##"$sel"}
	done <<- EOT
		$entries
	EOT

}

apps() {
	local entries=$(
		cat <<- EOT
			Archiver	xarchiver
			Calculator	gnome-calculator
			The GIMP	gimp
			Image Viewer	geeqie ${HOME}/Pictures
			Office Suite	libreoffice
		EOT
	)
	menu "$entries"
}

display() {
	local entries=$(
		cat <<- EOT
			□ LVDS		dmenu-xrandr LVDS
			□ HDMI		dmenu-xrandr HDMI
			□ VGA		dmenu-xrandr VGA
			-------------------
			‖ LVDS - HDMI	dmenu-xrandr LVDS-HDMI
			‖ HDMI - LVDS	dmenu-xrandr HDMI-LVDS
			‖ LVDS - VGA	dmenu-xrandr LVDS-VGA
			‖ VGA - LVDS	dmenu-xrandr VGA-LVDS
			‖ HDMI - VGA	dmenu-xrandr HDMI-VGA
			‖ VGA - HDMI	dmenu-xrandr VGA-HDMI
			-------------------
			= LVDS - HDMI	dmenu-xrandr LVDS+HDMI
			= HDMI - LVDS	dmenu-xrandr HDMI+LVDS
			= LVDS - VGA	dmenu-xrandr LVDS+VGA
			= VGA - LVDS	dmenu-xrandr VGA+LVDS
			= HDMI - VGA	dmenu-xrandr HDMI+VGA
			= VGA - HDMI	dmenu-xrandr VGA+HDMI
			-------------------
			Custom
		EOT
	)
	menu "$entries" "Display:"
}

kbd() {
	local entries=$(
		cat <<- EOT
			Italian		setxkbmap -layout it,us -option grp:shift_caps_toggle -option caps:menu
			English-US	setxkbmap -layout us,it -option grp:shift_caps_toggle -option caps:menu
		EOT
	)
	menu "$entries" "Kbd Layout:"
}

desktop() {
	local entries=$(
		cat <<- EOT
			Open Desktop Folder	x-filemanager ${HOME}/Desktop
			-------------------
			Documents		x-filemanager ${HOME}/Documents
			Downloads		x-filemanager ${HOME}/Downloads
			Music			x-filemanager ${HOME}/nfs/music
			Pictures		geeqie ${HOME}/nfs/photos
			Videos			x-filemanager ${HOME}/nfs/videos
			-------------------
			Background		nitrogen ${HOME}/Pictures/wallpapers
		EOT
	)
	menu "$entries" "Desktop:"
}

screenshot() {
	local entries=$(
		cat <<- EOT
			Whole Desktop		screenshot desktop
			Select Window/Area	screenshot
		EOT
	)
	menu "$entries" "Screenshot:"
}

# main {
	entries=$(
		cat <<- EOT
			Terminal Emulator	x-terminal-emulator
			Web Browser		x-web-browser
			E-Mail Client		x-email-client
			Filemanager		x-filemanager
			Text Editor		x-text-editor
			-------------------
			Common Apps...		apps
			Run...			dmenu_run-cust -p Run:
			-------------------
			Display Settings...	display
			Keyboard Layout...	kbd
			Removable Devices	x-terminal-emulator -T "Removables" -e amount-wrapper
			-------------------
			Desktop...		desktop
			Play URL in Clip	play-url -p
			Screenshot...		screenshot
			Timer...		dmenu-timer
			-------------------
			Exit Session		x-session-logout
		EOT
	)
	menu "$entries"
# }
