#!/bin/sh

# ----------------------------------------------------------------------
#  $Id$
#
#  Change display settings using dmenu
# ----------------------------------------------------------------------

# No output msgs, please
exec >/dev/null 2>&1

MENU_ITEMS="\
$(for f in ~/.screenlayout/*; do
        f=${f##*/}; printf "%s\\\n" ${f%%.*}
done)\
Custom"

LVDS="$(xrandr -q | grep -w connected | awk '{print $1}' | grep LVDS)"
 VGA="$(xrandr -q | grep -w connected | awk '{print $1}' | grep VGA)"
HDMI="$(xrandr -q | grep -w connected | awk '{print $1}' | grep HDMI)"
  DP="$(xrandr -q | grep -w connected | awk '{print $1}' | grep DP)"
if [ -z "$VGA" ] && [ -z "$HDMI" ] && [ -z "$DP" ]; then
        echo -e "No dual monitor configuration available" |
        xmessage -center -title "dmenu-xrandr" \
                -buttons "Close":0,"Reset Display":2 -file -
        [ "$?" -eq 2 ] && xrandr --auto
        exit 1
fi

if [ -n "$1" ]; then
        cmd="$1"
else
        cmd="$(echo -e $MENU_ITEMS | dmenu-cust -p "Screen Layout:" "$@")"
fi

case "$cmd" in
Custom)
        exec arandr ;;
LVDS)
        xrandr \
            --output "$LVDS" --auto \
            --output "$VGA" --off \
            --output "$HDMI" --off \
            --output "DP" --off
        ;;
VGA)
        xrandr \
            --output "$LVDS" --off \
            --output "$VGA" --auto \
            --output "$HDMI" --off \
            --output "DP" --off
        ;;
HDMI)
        xrandr \
            --output "$LVDS" --off \
            --output "$VGA" --off \
            --output "$HDMI" --auto \
            --output "DP" --off
        ;;
DP)
        xrandr \
            --output "$LVDS" --off \
            --output "$VGA" --off \
            --output "$HDMI" --off \
            --output "DP" --auto
        ;;
*)
        exec ~/.screenlayout/${cmd}.sh
esac

