#!/bin/sh

# ----------------------------------------------------------------------
#  $Id$
#
#  Simple filebrowser using dmenu and xdg-open
# ----------------------------------------------------------------------

LATEST="/tmp/$USER.dmenu-filebrowser.latest"
touch "$LATEST"

OPWD="$PWD"
NODE="$PWD"
while :; do
        NODE="$(([ "$PWD" == "$OPWD" ] && cat "$LATEST"; echo ".."; ls -AF1) |
                dmenu-cust -p $(echo "$PWD" | tr " " _) -i -l 20)" || exit
        NODE="$(echo $NODE | sed "s/[/@*=|]$//")"
        [ ! -d "$NODE" ] && break || cd "$NODE"
done

if [ "$PWD" != "$OPWD" ] && ! grep -Fx "$PWD/" "$LATEST"; then
        (echo "$PWD/" && cat "$LATEST") | head -5 > "$LATEST".tmp
        mv -f "$LATEST"{.tmp,}
fi


case "$NODE" in
*.m2ts) mpv "$NODE" ;;
     *) xdg-open "$NODE"
esac
