#!/bin/sh

# ----------------------------------------------------------------------
#  $Id$
#
#  Logout from current session (or suspend/reboot/poweroff the machine)
#  using dmenu
# ----------------------------------------------------------------------

# No output msgs, please
exec >/dev/null 2>&1

_array() {
        case "$SH_VERSION" in
        *KSH*)
                a="$1"; shift
                set -A "$a" "$@"
                ;;
        *)
                eval $1='("${@:2}")'
        esac
}

_array MENU_ITEMS \
        "Logout" \
        "Suspend" \
        "Hibernate" \
        "Reboot" \
        "Poweroff"

case "$(printf "%s\n" "${MENU_ITEMS[@]}" |
        dmenu-cust -p "Exit Session:" "$@")" in
Logout)
        # Next login should start from a known display configuration...
        case "$(xrandr -q | grep -E "[0-9]+x[0-9]+\+[0-9]+\+[0-9]+" | head -n 1 | cut -d" " -f1)" in
        LVDS*) dmenu-xrandr -d Off ;;
        VGA*)  dmenu-xrandr -d Only ;;
        esac

        case "$XSESSION_CMD" in
        *fluxbox*)
                pkill -P "$(cat /tmp/dbar.pid)"
                rm /tmp/dbar.pid
                fluxbox-remote Exit
                ;;
        *xfce*)
                xfce4-session-logout --logout --fast
                ;;
        dwm*)
                pkill dwm
                ;;
        cwm|twm)
                pkill "$XSESSION_CMD"
                ;;
        *openbox*)
                openbox --exit
                ;;
        esac
        ;;
Suspend)
        /usr/sbin/zzz
        ;;
Hibernate)
        /usr/sbin/ZZZ
        ;;
Reboot)
        /usr/bin/doas /sbin/reboot
        ;;
Poweroff)
        /usr/bin/doas /sbin/shutdown -p now
        ;;
esac
