#!/bin/sh

# ----------------------------------------------------------------------
#  $Id$
#
#  xautolock control
# ----------------------------------------------------------------------

run() {
        case "$(echo -e $MENU_ITEMS | dmenu -p xautolock: "$@")" in
        Enable)
                xautolock -enable
                ;;
        Disable)
                xautolock -disable
                ;;
        Lock)
                xautolock -locknow
                ;;
        Restart)
                xautolock -restart
                ;;
        Launch)
                xautolock -detectsleep -time 10 -locker lock-screen &
                ;;
        Exit)
                xautolock -exit
                ;;
        esac
}

MENU_ITEMS="\
Lock\n\
Enable\n\
Disable\n\
Restart\n\
Launch\n\
Exit"

outMsg="$(run 2>&1)"
[ -n "$outMsg" ] && notify-send xautolock "$outMsg"
