#!/bin/sh

# ----------------------------------------------------------------------
#  $Id$
#
#  Logout from current session (or suspend/reboot/poweroff the machine)
#  using dmenu
# ----------------------------------------------------------------------

# No output msgs, please
exec >/dev/null 2>&1

_array() {
        case "$SH_VERSION" in
        *KSH*)
                a="$1"; shift
                set -A "$a" "$@"
                ;;
        *)
                eval $1='("${@:2}")'
        esac
}

_array MENU_ITEMS \
        "Logout" \
        "Suspend" \
        "Hibernate" \
        "Reboot" \
        "Poweroff"

case "$(printf "%s\n" "${MENU_ITEMS[@]}" |
        dmenu-cust -p Quit: "$@")" in
Logout)
        case "$XSESSION_CMD" in
        *fluxbox*)
                fluxbox-remote Exit
                ;;
        *xfce*)
                xfce4-session-logout --logout --fast
                ;;
        dwm*)
                pkill dwm
                ;;
        cwm|twm)
                pkill "$XSESSION_CMD"
                ;;
        *openbox*)
                openbox --exit
                ;;
        *jwm*)
                pkill jwm
                ;;
        *)
                ;;
        esac
        ;;
Suspend)
        /usr/sbin/zzz
        ;;
Hibernate)
        /usr/sbin/ZZZ
        ;;
Reboot)
        /usr/bin/doas /sbin/reboot
        ;;
Poweroff)
        /usr/bin/doas /sbin/shutdown -p now
        ;;
esac
