#!/bin/sh

# ----------------------------------------------------------------------
#  $Id$
#
#  Change display settings using dmenu
# ----------------------------------------------------------------------

# No output msgs, please
exec >/dev/null 2>&1

set -A MENU_ITEMS \
        "Off (LVDS-only)" \
        "Only (LVDS-off)" \
        "Left-of" \
        "Right-of" \
        "Above" \
        "Below"

LVDS="$(xrandr -q | grep -w connected | awk '{print $1}' | grep LVDS)"
 VGA="$(xrandr -q | grep -w connected | awk '{print $1}' | grep VGA)"
echo $LVDS
echo $VGA
if [ -z "$LVDS" ] || [ -z "$VGA" ]; then
        echo "No dual monitor configuration available" |
        xmessage -center -title "dmenu-xrandr" -buttons "Close" -file -
        exit 1
fi

case "$(printf "%s\n" "${MENU_ITEMS[@]}" |
        dmenu-cust -p VGA: "$@")" in
Off*)   wmrestart --output "$LVDS" --auto --output "$VGA" --off ;;
Only*)  wmrestart --output "$LVDS" --off  --output "$VGA" --auto ;;
Left*)  wmrestart --output "$LVDS" --auto --primary --output "$VGA" --auto --left-of  "$LVDS" ;;
Right*) wmrestart --output "$LVDS" --auto --primary --output "$VGA" --auto --right-of "$LVDS" ;;
Above)  wmrestart --output "$LVDS" --auto --primary --output "$VGA" --auto --above    "$LVDS" ;;
Below)  wmrestart --output "$LVDS" --auto --primary --output "$VGA" --auto --below    "$LVDS" ;;
*)      exit 1
esac

# Reset desktop (background, statusbar, ...)
wmrestart
