#!/bin/sh

# ----------------------------------------------------------------------
#  $Id$
#
#  Print user's most recent pdf file in tmp
# ----------------------------------------------------------------------

wmsg() {
        if gdbus call --session --dest org.freedesktop.DBus \
                      --object-path /org/freedesktop/Dbus \
                      --method org.freedesktop.DBus.ListNames
        then
                notify-send "Print to lpr" "$1"
        else
                echo -e "$1" |
                xmessage -title "Print to lpr" \
                         -buttons "OK":0 \
                         -file - &
        fi
}

MENU_ITEMS="\
draft\n\
normal\n\
hq\n\
draft-color\n\
normal-color\n\
hq-color"

q="${1-$(echo -e $MENU_ITEMS | dmenu -p "Print to lpr:" "$@")}"

if [ -n "$q" ]; then
        f="$(find /tmp -maxdepth 1 -type f -name "*.pdf" -user $USER -print0 |
             xargs -0 ls -1tr | tail -n 1)"
        if [ -n "$f" ]; then
                outMsg="$(lpr -P"lp-$q" "$f" 2>&1)"
                [ -z "$outMsg" ] && outMsg="File $f sent to lp-$q queue"
                wmsg "$outMsg"
        else
                wmsg "No PDF file found in /tmp"
        fi
fi
