#!/bin/sh

# ----------------------------------------------------------------------
#  $Id$
#
#  Keyboard layout switcher
# ----------------------------------------------------------------------

cl="$(setxkbmap -query | grep layout)"
nl="$(
        dmenu-cust -p "Kbd Layout [${cl##* }]:" <<- EOT
		it
		us
	EOT
)"

[ -n "$nl" ] && setxkbmap "$nl"
