#!/bin/sh

# ----------------------------------------------------------------------
#  $Id$
#
#  Select browser using dmenu
# ----------------------------------------------------------------------

MENU_ITEMS="\
firefox\n\
chrome\n\
surf-launcher"

echo $MENU_ITEMS |
    dmenu-cust -p "Network browser:" "$@" | ${SHELL:-/bin/sh}
