#!/bin/sh

# ----------------------------------------------------------------------
#  $Id$
#
#  dwm session manager
# ----------------------------------------------------------------------

# System log
(sleep 1; pkill xconsole) &
xterm -title "System log" -e tail -f /var/log/messages &

# System statistics
xterm -title "System stats" -e systat &

# Process monitor
xterm -title "Process monitor" -e top &

# Set root window background & wallpaper
xsetroot -solid rgb:58/6E/75
nitrogen --restore

# Restore wallpaper image upon resolution change
pkill -x xeventbind; xeventbind resolution wprestore &

# Statusbar
slstatus &

# Tray apps
vol-tray &
sed -i "s/mainwindow_xoffset = 0/mainwindow_xoffset = 10000/" \
    ~/.config/gsimplecal/config
cal-tray &

while :
do
        # Following apps live in the systray and will die every time dwm exits
        radiotray &

        # Start dwm and log errors in ~/.dwm.log
        mv ~/.dwm.log{,.old}
        dwm 2> ~/.dwm.log || exit
done

