#!/bin/sh

# ----------------------------------------------------------------------
#  $Id$
#
#  dwm session manager
# ----------------------------------------------------------------------

# Fix problems with JDK assuming a reparenting window manager
wmname LG3D 2>/dev/null

# Set root window background
xsetroot -solid rgb:58/6E/75

# Statusbar
if ! pgrep -x slstatus; then
        slstatus &
fi

# Site specific init file
[ -f ~/.dwm-session-init ] && . ~/.dwm-session-init

while :
do
        # Site specific startup file
        [ -f ~/.dwm-session-startup ] && . ~/.dwm-session-startup

        # Start dwm and log errors in ~/.dwm.log
        mv ~/.dwm.log{,.old}
        dwm 2> ~/.dwm.log || exit
done

