#!/bin/sh

# ----------------------------------------------------------------------
#  $Id$
#
#  dzen2 launcher with custom settings
# ----------------------------------------------------------------------

dzen2 -title-name "bar" \
      -expand left \
      -fg "#073642"  \
      -bg "#eee8d5"  \
      -fn "-*-dejavu sans mono-medium-r-*-*-12-*-*-*-*-*-*-*" \
      -h  17 \
      -dock \
      "$@"

