#!/bin/sh

# ----------------------------------------------------------------------
#  $Id$
#
#  Restart fluxbox and apps (typically after a screen resolution change)
# ----------------------------------------------------------------------

# Clean up statusbar
pkill -x bbpager
pkill -x space_dapp
#pcmanfm --desktop-off

fluxbox-remote Restart

sleep 2
space_dapp $((($(screen-width) - 1))) 17 &
dbar -geometry +0+1 -xs "${xs:-1}" &
sleep 1; bbpager &

nitrogen --restore || fbsetbg -l

#pcmanfm --desktop &

