#!/bin/sh

# ----------------------------------------------------------------------
#  $Id$
#
#  Simple firefox launcher (reuse current instance if already running)
# ----------------------------------------------------------------------

xdotool search -sync -name ".*- Mozilla Firefox$" windowactivate &
firefox-esr $@ &
