#!/bin/sh

# ----------------------------------------------------------------------
#  $Id$
#
#  Simple firefox launcher (reuse current instance if already running)
# ----------------------------------------------------------------------

firefox-esr $@ &
xdotool search -sync -name ".*- Mozilla Firefox$" windowactivate
