#!/bin/sh

# ----------------------------------------------------------------------
#  $Id$
#
#  Force full mailboxes synchronization, restarting offlineimap thereads
# ----------------------------------------------------------------------

if [ "$1" == -q ]; then
        pkill -QUIT -f /usr/local/bin/offlineimap
        offlineimap -s -u syslog -c ~/.offlineimaprc-sandro.delaurenzis@gmail.com &
        offlineimap -s -u syslog -c ~/.offlineimaprc-just22@atlantide.t28.net &
else
        pkill -USR1 -f /usr/local/bin/offlineimap
fi
