#!/bin/sh

# ----------------------------------------------------------------------
#  $Id$
#
#  Get xroot window's name (useful for system monitoring "a-la-dwm")
# ----------------------------------------------------------------------

printf " %s \n" "$(xwininfo -root | grep "^xwininfo:" | cut -d\" -f2)"
