#!/bin/sh

# File:         load_bookmark
# Purpose:      Load bookmark; specifically written for suckless surf browser,
#               may be adapted.
# Author:       A. DE LAURENZIS

BOOKMARK_FILE="${HOME}/.surf/bookmarks"

grep "$(cat "$BOOKMARK_FILE" | cut -d " " -f 2- | dmenu -i -l 10)" "$BOOKMARK_FILE" |
        awk -F ", " '{print $1}'

exit 0
