#!/bin/sh

# ----------------------------------------------------------------------
#  $Id$
#
#  Loads a bookmark; specifically written for suckless surf browser,
#  it may be adapted.
# ----------------------------------------------------------------------

BOOKMARK_FILE="${HOME}/.surf/bookmarks"

BM="$(cat "$BOOKMARK_FILE" | cut -d " " -f 2- | dmenu -i -l 10)"
[ -n "$BM" ] && grep -F "$BM" "$BOOKMARK_FILE" | awk -F ", " '{print $1}'

exit 0
