#!/bin/sh

# ----------------------------------------------------------------------
#  $Id$
#
#  Lock the screen (except when active window is in fullscreen mode)
#  usign slock
# ----------------------------------------------------------------------

w_act="$(xprop -root _NET_ACTIVE_WINDOW)"

while IFS='' read line; do
        case "$line" in
        _NET_WM_STATE*_NET_WM_STATE_FULLSCREEN*)
                exit 1
        esac
done <<- EOT
	$(xprop -id "${w_act##*# }")
EOT

exec slock
