#!/bin/sh

# ----------------------------------------------------------------------
#  $Id$
#
#  Low battery warning
# ----------------------------------------------------------------------

lt=$(apm -m)
hh="$(($lt / 60))"
mm="$(($lt % 60))"

printf "Low battery level (lifetime: %d:%02d)" "$hh" "$mm" |
xmessage -title "Low battery" -center -buttons "OK":0,"Hibernate":2 -file -

[ "$?" -eq 2 ] && apm -Z
