#!/bin/sh

# ----------------------------------------------------------------------
#  $Id$
#
#  Search for keywords in man pages
# ----------------------------------------------------------------------

set -e

usage() {
        >&2 echo "Usage: ${0##*/} <manpage> <keyword>"
        return 1
}

[ "$1" == -h -o $# -ne 2 ] && usage

man $1 | LESS="-F" less -p "^ +$2 +"
