#!/bin/sh

# ----------------------------------------------------------------------
#  $Id$
#
#  OpenBSD CVS src/xenocara/ports fetch/update helper
# ----------------------------------------------------------------------

_usage() {
        echo "Usage: ${0##*/}: -h | <op> <dir> [<tag>]"
        echo "       -h: This help message"
        echo "       <op>:=<checkout|update> Operation to perform"
        echo "       <dir>:=<src|xenocara|ports> Directory to fetch/update"
        echo "       <tag>:=<OPENBSD_x_x> Tag of stable branch, current if none"
}

# Command line positional arguments parsing
if [ "$1" == -h ] || [ "$#" -lt 2 ] || [ "$#" -gt 3 ]; then
        >&2 _usage
        exit 1
fi

# CVSROOT
export CVSROOT="anoncvs@anoncvs.fr.openbsd.org:/cvs"

cd /usr/"$2" 2>/dev/null
if [ "$?" -ne 0 ]; then
        >&2 echo "${0##*/}: Unknown directory"; exit 1
fi

# Optional stable tag
[ -n "$3" ] && r_opt="-r$3"

case "$1" in
checkout) echo $CVSROOT; cd ..; cvs -q get $r_opt -P "$2" ;;
update)   cvs -q update $r_opt -Pd ;;
*)        >&2 echo "${0##*/}: Unknown operation"; exit 1
esac

exit 0
