#!/bin/sh

# ----------------------------------------------------------------------
#  $Id$
#
#  Open removable devices automount directory
# ----------------------------------------------------------------------

[ -d /run/media/${USER} ] &&
        exo-open --launch FileManager /run/media/${USER}
