#!/bin/sh

# Usage:        open-removables-dir
# Purpose:      Open removable devices automount directory
# Author:       A. DE LAURENZIS

[ -d /run/media/${USER} ] &&
        exo-open --launch FileManager /run/media/${USER}
