#!/bin/sh

# ----------------------------------------------------------------------
#  $Id$
#
#  Plays Youtube (or similar) video (url in clipboard)
#  Dependencies: xclip, youtube-dl, smplayer, curl
# ----------------------------------------------------------------------

__usage() {
        echo "Usage: $(basename $0) [-h] [-t|-g] -p|-s|-c|<URL>"
        echo "-h This help message"
        echo "-t Use curl to transfer URL data"
        echo "-g Use mplayer GUI (smplayer)"
        echo "-p URL in XA_PRIMARY"
        echo "-s URL in XA_SECONDARY"
        echo "-c URL in XA_CLIPBOARD"
}

if [[ $# -lt 1 ]] || [[ $# -gt 2 ]]; then
        __usage
        exit 1
fi

while [ $# -gt 0 ]; do
        case "$1" in
        -h)
                __usage
                exit 0
                ;;
        -t)
                USE_CURL=1
                ;;
        -g)
                PLAYER="smplayer"
                ;;
        -p)
                URL_IN_CLIP=primary
                ;;
        -s)
                URL_IN_CLIP=secondary
                ;;
        -c)
                URL_IN_CLIP=clipboard
                ;;
        *)
                URL="$1"
                ;;
        esac
        shift
done

URL="${URL-$(xclip -o -selection $URL_IN_CLIP)}"
PLAYER="${PLAYER-mplayer}"
if [ -z "$URL" ]; then
        echo "$(basename $0): No URL in clipboard"
        exit 1
fi

if [ -n "$USE_CURL" ]; then
        curl -s $(youtube-dl -f best -g $URL) | $PLAYER -cache 4096 -
else
        $PLAYER $URL
fi

[ -n "$URL_IN_CLIP" ] && (cat /dev/null | xclip -selection $URL_IN_CLIP)

exit 0
