#!/bin/sh

# ----------------------------------------------------------------------
#  $Id$
# ----------------------------------------------------------------------

ytdl-smplayer $(xclip -o -selection clipboard)
cat /dev/null | xclip -selection clipboard
