#!/bin/sh

# ----------------------------------------------------------------------
#  $Id$
#
#  Simple reminder (using at and xmessage)
# ----------------------------------------------------------------------

echo -n "Time [see at(0)]: [+ 5 min] "; read TIME
echo -n "Message: [Foo] "; read MSG
echo -n "Snooze time: [300] "; read SNOOZE_TIME

[ -z "$TIME" ]        && TIME="now + 5 min"
[ -z "$MSG"  ]        && MSG="Foo"
[ -z "$SNOOZE_TIME" ] && SNOOZE_TIME=300

SHELL=/bin/sh at "$TIME" >/dev/null <<-EOT
	while true; do
		echo "$MSG" |
		DISPLAY="$DISPLAY" xmessage -title "Reminder" -center \
					-buttons "Got it":0,"Snooze":2 \
					-file - >/dev/null 2>&1
		[ "\$?" -eq 0 ] && break
		sleep $SNOOZE_TIME
	done
EOT
