#!/bin/sh

# File:         reminder
# Purpose:      Simple reminder (using at and xmessage)
# Author:       A. DE LAURENZIS

echo -n "Time [see at(1)]? "; read TIME
echo -n "Message? "; read MSG

SHELL=/bin/sh at "$TIME" >/dev/null <<-EOT
	while /bin/true; do
		echo "$MSG" |
		DISPLAY="$DISPLAY" xmessage -title "Reminder" -center \
					-buttons "Got it":0,"Snooze (5 min)":2 \
					-file - >/dev/null 2>&1
		[ "\$?" -eq 0 ] && break
		sleep 300
	done
EOT
