#!/bin/sh

# ----------------------------------------------------------------------
#  $Id$
#
#  Return the current screen's width
# ----------------------------------------------------------------------

# Note: in case of multi-head configs, the primary monitor will be
#       assumed as target (or the one in +0+0 if no primary is set)

w="$(xrandr -q |
     grep -w connected |
     grep -w primary |
     grep -Eo "[0-9]+x[0-9]" |
     cut -dx -f1)"

[ -z "$w" ] &&
w="$(xrandr -q |
     grep -w connected |
     grep -Eo "[0-9]+x[0-9]+\+0\+0" |
     cut -dx -f1)"

echo $w
