#!/bin/sh

# ----------------------------------------------------------------------
#  $Id$
#
#  Return the current screen's width
# ----------------------------------------------------------------------

# Note: in case of multi-head configs, the monitor in 0x0 will be
#       assumed as target

xrandr -q |
grep -w connected |
grep -Eo "[0-9]+x[0-9]+\+0\+0" |
cut -dx -f1

