#!/bin/sh

# ----------------------------------------------------------------------
#  $Id$
#
#  Select the X session to start
#  (link this executable to ~/.start-xsession when needed)
# ----------------------------------------------------------------------

exec `Xdialog --buttons-style text                \
              --no-close                          \
              --no-cancel                         \
              --no-tags                           \
              --screen-center                     \
              --stdout                            \
              --menubox                           \
                  "Select the X session"          \
                  195x133                         \
                  3                               \
                  "dwm-session"         "dwm"     \
                  "startfluxbox"        "fluxbox" \
                  "twm-session"         "twm"`    ||
exec twm

