#!/bin/sh

# ----------------------------------------------------------------------
#  $Id$
#
#  Logout from current session (or suspend/reboot/poweroff the machine)
#  using Xdialog
# ----------------------------------------------------------------------

echo $XSESSION_CMD
DIALOG=Xdialog

$DIALOG --title "Exit Session" \
        --radiolist "Please select an action:" 18 50 0 \
                "Logout"        "Exit from current X session"   off \
                "Suspend"       "Suspend to RAM"                off \
                "Hibernate"     "Suspend to disk"               ON  \
                "Reboot"        "Reboot the system"             off \
                "Poweroff"      "Shut down the computer"        off \
        2>/tmp/checklist.tmp.$$

RETVAL=$?
CHOICE=`cat /tmp/checklist.tmp.$$`
rm -f /tmp/checklist.tmp.$$

if [ $RETVAL -eq 0 ]; then
        case "$CHOICE" in
        Logout)
                if pgrep -x dwm; then
                        pkill -x dwm
                elif pgrep -x fluxbox; then
                        pkill -P "$(cat /tmp/dbar.pid)"
                        rm /tmp/dbar.pid
                        fluxbox-remote Exit
                elif pgrep -x cwm; then
                        pkill -P "$(cat /tmp/dbar.pid)"
                        rm /tmp/dbar.pid
                        pkill -x cwm
                elif pgrep -x xfwm4; then
                        xfce4-session-logout --logout --fast
                elif pgrep -x openbox; then
                        openbox --exit
                else
                        pkill -x twm
                fi
                ;;
        Suspend)
                /usr/sbin/zzz
                ;;
        Hibernate)
                /usr/sbin/ZZZ
                ;;
        Reboot)
                /usr/bin/doas /sbin/reboot
                ;;
        Poweroff)
                /usr/bin/doas /sbin/shutdown -p now
                ;;
        esac
fi
