#!/bin/sh

# File:         set_display
# Purpose:      External monitors management
# Author:       Alessandro DE LAURENZIS <just22.adl@gmail.com>
# Version:      2.x
# Date:         Jul 2016

# No output msgs, please
exec >/dev/null 2>&1

# Clean up statusbar area
pkill -x dzen2
pkill -x space_dapp

# Turn off desktop manager
pcmanfm --desktop-off

# Change display layout
xrandr $@

# Restart statusbar
(sleep 1; statusbar) &
(sleep 2; space_dapp) &

# Restart window manager
if pgrep -x fluxbox; then
        fbsetroot -gradient Vertical -from rgb:07/36/42 -to rgb:58/6E/75
        fluxbox-remote restart
elif pgrep -x openbox; then
        xsetroot -solid rgb:58/6E/75
        #openbox --restart
elif pgrep -x fvwm2; then
        xsetroot -solid rgb:58/6E/75
        FvwmCommand Restart
fi

# Wallpaper setting
[ -x ~/.fehbg ] && ~/.fehbg

# Launch desktop manager
pcmanfm --desktop
