#!/bin/sh

# File:         set_display
# Purpose:      External monitors management
# Author:       Alessandro DE LAURENZIS <just22.adl@gmail.com>
# Version:      1.0
# Date:         Somewhere in time...

if [ "$#" != 3 ]; then
        echo "Usage: $0 <disp1> <disp2> <pos|only|restore>"
        exit 1
fi

exec >/dev/null 2>&1

DISPLAY_1=$1
DISPLAY_2=$2
ACTION=$3

if [ "$ACTION" == only ]; then
        xrandr --output $DISPLAY_1 --off --output $DISPLAY_2 --auto
elif [ "$ACTION" == restore ]; then
        #sudo wsconsctl display.focus=4; xrandr --output $DISPLAY_1 --auto --output $DISPLAY_2 --off
        xrandr --auto
else
        xrandr --output $DISPLAY_1 --auto --primary --output $DISPLAY_2 --auto --$ACTION $DISPLAY_1
fi

hsetroot -add '#073642' -add '#586E75' -gradient 0

if pgrep -x openbox; then
        openbox --restart
        feh --bg-scale ~/Images/Wallpapers/apple_keyboard.jpg
fi

if pgrep -x bbpager; then
        pkill bbpager; bbpager&
fi

if pgrep -x tint2; then
        pkill tint2
        case "$ACTION" in
        above|below):
                tint2 -c ~/.config/tint2/dual_aboveBelow.tint2rc&
                ;;
        *):
                tint2&
                ;;
        esac
fi

sleep 2
pkill conky; conky-statusbar&
