#!/bin/sh

# File:		sys-backup
# Usage:	sys-backup [<configFineName>]
# Purpose:	system files' backup usign rsync --link-dest
# Author:	A. DE LAURENZIS


# ----------------------------------------------------------------------
# Config section
# (All variables in this secition can be set in a separated config file)
#
DIR_LIST="/etc /var"
DAYS_BEFORE_DELETION="7"

# Default values for the following variables shouldn't be changed
TSTAMP="%Y%m%d_%R"
TMP_DIR="/tmp"
BACKUP_REPO="/mnt/sys_backup/$(hostname)"
# ----------------------------------------------------------------------


if [ $# != 0 ]; then
	if [ -f "$1" ]; then
		. "$1"
	else
		echo "sys-backup: file $1 not fount; continuing with default config" >&2
		logger -t sys-backup "file $1 not fount; continuing with default config"
	fi
fi

if ! [ -d "$BACKUP_REPO" ]; then
	echo "sys-backup: Cannot find back-up repo $BACKUP_REPO (not mounted?)" >&2
	logger -t sys-backup "Cannot find back-up repo $BACKUP_REPO (not mounted?)"
	exit 1
fi

if [ -f "${TMP_DIR}/sys-backup.pid" ]; then
	PID=$(cat "${TMP_DIR}/sys-backup.pid")
	echo "sys-backup: Previous instance still running (pid=$PID), or stale ${TMP_DIR}/sys-backup.pid" >&2
	logger -t sys-backup "Previous instance still running (pid=$PID), or stale ${TMP_DIR}/sys-backup.pid"
	exit 2
fi

PREV_BACKUP_DIR="${BACKUP_REPO}/$(ls -Atr $BACKUP_REPO | tail -n 1)"
BACKUP_DIR="${BACKUP_REPO}/$(date +$TSTAMP)"
if ! mkdir "$BACKUP_DIR" 2>/dev/null; then
	echo "sys-backup: $BACKUP_DIR: directory already exists; back-up run too early?" >&2
	logger -t sys-backup "$BACKUP_DIR: directory already exists; back-up run too early?"
	exit 3
fi

echo "$$" > ${TMP_DIR}/sys-backup.pid

for SRC_DIR in $DIR_LIST; do
	if [ -d "$SRC_DIR" ]; then
		if [ -d "$PREV_BACKUP_DIR${SRC_DIR}" ]; then
			rsync -azHx --link-dest="${PREV_BACKUP_DIR}${SRC_DIR}" "$SRC_DIR/" "${BACKUP_DIR}${SRC_DIR}"
		else
			rsync -azHx "$SRC_DIR" "$BACKUP_DIR"
		fi
		if [ "$?" != 0 ]; then
			echo "sys-backup: Back-up of $SRC_DIR: rsync exited with error code $?" >&2
			logger -t sys-backup "Back-up of $SRC_DIR: rsync exited with error code $?"
			RSYNC_FAIL=1
		else
			echo "sys-backup: Back-up of $SRC_DIR done"
			logger -t sys-backup "Back-up of $SRC_DIR done"
		fi
	else
		echo "sys-backup: $SRC_DIR not found; script will continue..." >&2
		logger -t sys-backup "$SRC_DIR not found"
		SRC_DIR_FAIL=1
	fi
done

find "$BACKUP_REPO" -maxdepth 1 -type d -mtime $DAYS_BEFORE_DELETION -exec rm -rf {} \;

rm -rf ${TMP_DIR}/sys-backup.pid

if [ "$RSYNC_FAIL" == 1 ]; then
	echo "sys-backup: Script completed with rsync failures"
	logger -t sys-backup "Script completed with rsync failures"
	exit 4
elif [ "$SRC_DIR_FAIL" == 1 ]; then
	echo "sys-backup: Script completed with src dir failures"
	logger -t sys-backup "Script completed with src dir failures"
	exit 5
fi

echo "sys-backup: Script completed successfully"
logger -t sys-backup "Script completed successfully"
exit 0
