#!/bin/sh

# ----------------------------------------------------------------------
#  $Id$
#
#  Simple timer (using at and xmessage)
# ----------------------------------------------------------------------

while [ $# -ne 0 ]; do
        case "$1" in
        -i)
                INTERACTIVE=1
                ;;
        -t)
                shift
                TIME="$1"
                ;;
        -m)
                shift
                MSG="$1"
                ;;
        -s)
                shift
                SNOOZE_TIME="$1"
                ;;
        *)
                echo "Usage: $(basename $0) [-i] | [-t <time>] [-m <msg>] [-s <snoozeTime>]"
                exit 1
                ;;
        esac
        shift
done

if [ -n "$INTERACTIVE" ]; then
        echo -n "Time [see at(1)]: [now + 5 minutes] "; read TIME
        echo -n "Message: [Time's up!] "; read MSG
        echo -n "Snooze time [s]: [300] "; read SNOOZE_TIME
fi

TIME=${TIME:-"now + 5 minutes"}
MSG=${MSG:-"Time's up!"}
SNOOZE_TIME=${SNOOZE_TIME:-300}

SHELL=/bin/sh at "$TIME" 2>/tmp/$USER.timer.$$ <<-EOT
        while true; do
                echo "$MSG" |
                DISPLAY="$DISPLAY" xmessage -title "Reminder" -center \
                                        -buttons "Got it":0,"Snooze":2 \
                                        -file - >/dev/null 2>&1
                [ "\$?" -eq 0 ] && break
                sleep $SNOOZE_TIME
        done
EOT

if [ "$?" -eq 0 ]; then
        msg="Reminder set at:\n$(cat /tmp/$USER.timer.$$ |
                                 grep "^job" |
                                 awk -F " at " '{print $2}')"
else
        msg="Error: wrong time format?\n(Reminder not set)"
fi

echo $msg | xmessage -title "Reminder" -center \
                     -buttons "OK":0 \
                     -file - >/dev/null 2>&1
rm -r /tmp/$USER.timer.$$
exit 0
