#!/bin/sh

# ----------------------------------------------------------------------
#  $Id$
#
#  Simple timer (using at and xmessage)
# ----------------------------------------------------------------------

while [ $# -ne 0 ]; do
        case "$1" in
        -i)
                INTERACTIVE=1
                ;;
        -t)
                shift
                TIME="$1"
                ;;
        -m)
                shift
                MSG="$1"
                ;;
        -s)
                shift
                SNOOZE_TIME="$1"
                ;;
        *)
                echo "Usage: $(basename $0) [-i] | [-t <time>] [-m <msg>] [-s <snoozeTime>]"
                exit 1
                ;;
        esac
        shift
done

if [ -n "$INTERACTIVE" ]; then
        echo -n "Time [see at(0)]: [+ 5 min] "; read TIME
        echo -n "Message: [Time's up!] "; read MSG
        echo -n "Snooze time: [300] "; read SNOOZE_TIME
fi

TIME=${TIME:-"now + 5 min"}
MSG=${MSG:-"Time's up!"}
SNOOZE_TIME=${SNOOZE_TIME:-300}

SHELL=/bin/sh at "$TIME" >/dev/null <<-EOT
        while true; do
                echo "$MSG" |
                DISPLAY="$DISPLAY" xmessage -title "Reminder" -center \
                                        -buttons "Got it":0,"Snooze":2 \
                                        -file - >/dev/null 2>&1
                [ "\$?" -eq 0 ] && break
                sleep $SNOOZE_TIME
        done
EOT
