#!/bin/sh

# ----------------------------------------------------------------------
#  $Id$
#
#  Simple timer (using GNU date, sleep and xmessage)
# ----------------------------------------------------------------------

dmsg() {
        if gdbus call --session --dest org.freedesktop.DBus \
                      --object-path /org/freedesktop/Dbus \
                      --method org.freedesktop.DBus.ListNames 2>/dev/null
        then
                notify-send "Timer" "$(echo "$1")"
        else
                echo "$1"|
                xmessage -title "Timer" -center -buttons "OK":0 -file - \
                    >/dev/null 2>&1
        fi
}

while [ $# -ne 0 ]; do
        case "$1" in
        -i)
                INTERACTIVE=1
                ;;
        -t)
                shift
                TIME="$1"
                ;;
        -m)
                shift
                MSG="$1"
                ;;
        -s)
                shift
                SNOOZE_TIME="$1"
                ;;
        *)
                echo "Usage: ${0##*/} [-i] | [-t <time>] [-m <msg>] [-s <snoozeTime>]"
                exit 1
                ;;
        esac
        shift
done

if [ -n "$INTERACTIVE" ]; then
        echo -n "Time [see at(1)]: [now + 5 minutes] "; read TIME
        echo -n "Message: [Time's up!] "; read MSG
        echo -n "Snooze time [s]: [300] "; read SNOOZE_TIME
fi

TIME=${TIME:-"+5min"}
MSG=${MSG:-"Time's up!"}
SNOOZE_TIME=${SNOOZE_TIME:-300}

# GNU date is required, due to its conversion capabilities
case "$(uname -s)" in
OpenBSD) datecmd=gdate ;;
      *) datecmd=date
esac

tstamp="$($datecmd -d "$TIME" +"%a %d %b, %R" 2>/dev/null)"
if [ "$?" -ne 0 ]; then
        msg="Error: wrong time format?\n(Timeout not set)"
        dmsg "$msg"
        exit 1
fi

msg="Timeout set at $tstamp"
dmsg "$msg" &

tout="$($datecmd -d "$TIME" +%s)"

# Check every minutes, to cope with suspend/hibernate
while : ; do
        sleep 60
        tnow="$($datecmd +%s)"
        [ $(($tout - $tnow)) -le 0 ] && break
done

while : ; do
        echo "$MSG" |
        DISPLAY="$DISPLAY" \
        xmessage -title "Timer" \
            -buttons "Got it":0,"Snooze":2 \
            -file - >/dev/null 2>&1
        [ "$?" -eq 0 ] && break
        sleep $SNOOZE_TIME
done

