#!/bin/sh

# ----------------------------------------------------------------------
#  $Id$
#
#  Open an existing tmux session (or connect to an existing one)
# ----------------------------------------------------------------------

SESSION_NAME="$1"
~/bin/tmux attach-session -d -t $SESSION_NAME || ~/bin/tmux new-session -s $SESSION_NAME
