#!/bin/sh

# ----------------------------------------------------------------------
#  $Id$
#
#  Tile panels (a-la-dwm) in a tmux window
# ----------------------------------------------------------------------

_usage() {
        echo "${0##*/} -h|-o|-v"
        echo "-h:    This message"
        echo "-o|-v: Tile panes horizontally|vertically"
}

if [ "$1" == "-o" ]; then
        tmux select-layout main-horizontal
        Y="$(($(tmux display -p '#{window_height}') / 2 - 1))"
        tmux resize-pane -t:.1 -y "$Y"
elif [ "$1" == "-v" ]; then
        tmux select-layout main-vertical
        X="$(($(tmux display -p '#{window_width}') / 2 - 1))"
        tmux resize-pane -t:.1 -x "$X"
else
        _usage
        if [ "$1" == "-h" ]; then
                exit 0
        else
                exit 1
        fi
fi

