#!/bin/sh

# ----------------------------------------------------------------------
#  $Id$
#
#  Toggle statusbar visibility (and its space reservation)
# ----------------------------------------------------------------------

if ! xdotool search --onlyvisible --class "dzen" windowunmap %@; then
        xdotool search --class "dzen" windowmap %@ windowraise %@
fi
