#!/bin/sh

# ----------------------------------------------------------------------
#  $Id$
#
#  Toggle statusbar visibility (and its space reservation)
# ----------------------------------------------------------------------

if xdotool search --onlyvisible --class "dzen" windowunmap; then
        pkill -x space_dapp
else
        xdotool search --class "dzen" windowmap windowraise
        space_dapp
fi
