#!/bin/sh

# ----------------------------------------------------------------------
#  $Id$
#
#  twm session manager
# ----------------------------------------------------------------------

# xidle daemon (corner locking virtually disabled, no timeout,
# activated by SIGUSR1)
if ! pgrep -u $UID -x xidle >/dev/null 2>&1; then
        xidle -delay 86400 -program ${HOME}/bin/xsession-lock &
fi

# Screen locker
xautolock -detectsleep -time 10 -locker lock-screen &

# dunst notification system
mkdir -p "${XDG_DATA_HOME:-$HOME/.local/share}/dbus-1/services"
ln -sf \
    "/usr/local/share/dbus-1/services/org.knopwob.dunst.service" \
    "${XDG_DATA_HOME:-$HOME/.local/share}/dbus-1/services/org.freedesktop.Notifications.service"

# Start a session bus instance of dbus-daemon
if [ -x /usr/local/bin/dbus-launch -a -z "${DBUS_SESSION_BUS_ADDRESS}" ]; then
        eval `dbus-launch --sh-syntax --exit-with-x11`
fi

# Statusbar
dbar -k
dbar -m cpu_mem -m load -m sd0 -m trunk0 -m mixer -m batt -m time -- \
     -ta r -xs "$xs" &

# Set wallpaper (or root window background)
nitrogen --restore || xsetroot -solid rgb:58/6E/75

# Start twm
mv ~/.twm/twm.log{,.old}
exec twm 2> ~/.twm/twm.log

