#!/bin/sh

# ----------------------------------------------------------------------
#  $Id$
#
#  Update XDG apps fluxbox's menu (depends on xdgmenumaker)
# ----------------------------------------------------------------------

xdgmenumaker -i -f fluxbox > ~/.fluxbox/menu-xdg_apps

item="Update XDG Apps"
cmd="update-xdg-apps-fbmenu"
icon="/usr/local/share/icons/gnome/16x16/apps/system-software-update.png"
echo "[exec] ($item) {$cmd} <$icon>" >> ~/.fluxbox/menu-xdg_apps
