#!/bin/sh

# ----------------------------------------------------------------------
#  $Id$
#
#  Return USB controller, port and addr associated with device name
#  (First release: 06 May 2014)
# ----------------------------------------------------------------------

if [ $# != 1 ]; then
    echo "Usage: usbdevinfo <deviceName>"
    exit 1
fi

usbdevs -v | awk -v deviceName=$1 '
    BEGIN {
        found=0;
        pattern="^[\t ]+driver: "deviceName"$"
    }
    found==1 {
        printf "Device name: %s\nController: %s\n%s\n", deviceName, controller, portAddr;
        exit
    }
    /Controller/ {
        controller=$2;
        sub(":$", "", controller)
    }
    /addr [0-9]+: / {
        portAddr=$0;
        sub("^[\t ]+", "", portAddr)
    }
    $0 ~ pattern {
        found=1
    }
    END {
        if (found==0) {print "Not found"}
    }
'
