#!/bin/sh

# File:         win_search
# Purpose:      Switch to selected window (searching for its class
#               and/or title)
# Dependencies: dmenu, wmctrl
# Author:       A. DE LAURENZIS

get_win_ids() {
        xprop -root |
                grep "^_NET_CLIENT_LIST(WINDOW)" |
                awk 'BEGIN{FS="#"} {print $2}' |
                tr -d ","
}

search_win() {
        for WIN_ID in $(get_win_ids); do
                WIN_CLASS="$(xprop -id $WIN_ID | grep "^WM_CLASS(STRING)" | awk '{print $4}')"
                WIN_TITLE="$(xprop -id $WIN_ID | grep "^WM_NAME(STRING)" | awk 'BEGIN{FS=" = "} {print $2}')"
                echo "$WIN_ID" "$WIN_CLASS" "$WIN_TITLE"
        done |
        dmenu -fn "-xos4-terminus-medium-*-*-*-14-*-*-*-*-*-iso10646-1" -nf "#93A1A1" -nb "#073642" -sb "#657B83" -i -l 5 |
        awk '{print $1}'
}

wmctrl -i -a $(search_win)
