#!/bin/sh

# ----------------------------------------------------------------------
#  $Id$
#
#  Perform a wmctrl action on selected window (by default, switch to
#  its desktop, raise and give it focus).
#  Dependencies: dmenu, wmctrl
# ----------------------------------------------------------------------

# No error msg, please!
exec 2>/dev/null

_usage() {
        echo "${0##*/} -h | [-z] [wmctrl opt]"
        echo "-h: This message"
        echo "-z: Desktop numbering starts from zero"
}

if [ "$1" == -h ]; then
        _usage
        exit 0
elif [ "$1" == -z ]; then
        d_inc=1
        shift
fi

win() {
        win_l="$(xprop -root _NET_CLIENT_LIST | egrep -o "0x[0-9a-fA-F]+")"
        win_c="$(echo $win_l | wc -w)"
        win_a=$(xprop -root _NET_ACTIVE_WINDOW | awk -F' ' '{ print $NF }')
        for win_id in $win_l; do
                [ "$win_id" == "$win_a" ] && tag="*" || tag=" "
                xprop -id "$win_id" |
                awk -v d_inc="${d_inc:-0}" -v id="$win_id" -v tag="$tag" '
                        /^_NET_WM_WINDOW_TYPE/  {if (match($0, "DOCK|DESKTOP")) {exit}}
                        /window state/          {if (match($0, "Iconic")) {tag = "h"}}
                        /^WM_CLASS/             {c = $4}
                        /^WM_NAME/              {t = ""; for(i = 3; i <= NF; ++i) t = (t $i " ")}
                        /^_NET_WM_DESKTOP/      {d = "(" $3 + d_inc ")"}
                        /^CUST_WM_LABEL/        {split($3, l, /"/)}
                        END                     {if (c != "" && t != "")
                                                        printf("%9.9s %s %s %-15s %-20.20s %s\n",
                                                             id, d, tag, "[" l[2] "]",
                                                             substr(c, 2, length(c) - 2),
                                                             substr(t, 2, length(t) - 3))
                                                }'

        done | sort -k2,2nr |
        dmenu-cust -p Win: -i -l "$win_c" | awk '{print $1}'
}

wmctrl -i ${1--a} "$(win)"

