#!/bin/ksh

# ----------------------------------------------------------------------
#  $Id$
#
#  Common window manager actions
#  Partially based on wmplus, optimized code
# ----------------------------------------------------------------------

_sinopsys() {
        echo "wmprocs tile [<tile_action>] [-g <tile_gap>] [-w <win_id>]"
        echo "wmprocs move2ws [<ws>] [-a] [-w <win_id>]"
        echo "wmprocs winaction [<win_action>] [-w <win_id>]"
        echo "wmprocs getwinid <searchStr>"
        echo "wmprocs mk_links|rm_links"
        echo "wmprocs help"
}

_usage() {
        echo "Usage:"
        _sinopsys
}

_help() {
        echo "NAME"
        echo "wmprocs - Common window management actions"
        echo
        echo "SINOPSYS"
        _sinopsys
        echo
        echo "DESCRIPTION"
        echo "This is a collection of common window management actions;"
        echo "used to be a \"poor man's window tiling\" tool, it is now"
        echo "a suite of procedures intended to integrete WS's capabilities."
        echo
        echo "The options are as follows:"
        echo
        echo "tile:"
        echo "{t,b,l,r} tiles window to the top (default), bottom, left"
        echo "or right;"
        echo "{h,v} tiles visible windows horizontally or vertically;"
        echo "-g specifies the tile gap between windows (default: 2px);"
        echo
        echo "move2ws:"
        echo "moves window to the specified workspace (by default,"
        echo "the current one); -a activates it;"
        echo
        echo "winaction:"
        echo "Performs various actions on current window:"
        echo "max:     toggles maximized window's state"
        echo "maxraise: same of max, but also raise the window"
        echo "kill:    kill a client by its X resource"
        echo
        echo "getwinid:"
        echo "gets id of the window matching <searchStr> in WM_CLASS or"
        echo "WM_TITLE fields;"
        echo
        echo "The id of the window may be specified through -w option;"
        echo "it defaults to the active one"
        echo
        echo "In order to simplify the procedure usage, the action may"
        echo "be specified through the command name itself: just make a"
        echo "symbolic link to wmprocs named as the intended action and"
        echo "launch the command with the link name."
        echo
        echo "Two procedures have been added to ease link management:"
        echo "mk_links makes symbolic links in the same directory where"
        echo "wmprocs is launched from;"
        echo "rm_links removes those links."
}

_array() {
        if [[ -n "$KSH_VERSION" || "$SH_VERSION" == *KSH* ]]; then
                a="$1"; shift
                set -A "$a" "$@"
        elif [ -n "$BASH_VERSION" ]; then
                eval $1='("${@:2}")'
        else
                >&2 echo "${0##*/}: Error: This shell doesn't support arrays"
                exit 1
        fi
}

get_root_win_props() {
        xprop -root _NET_CLIENT_LIST _NET_ACTIVE_WINDOW _NET_CURRENT_DESKTOP |&
        while read -p line; do
                case "$line" in
                *_NET_CLIENT_LIST*)
                        _WIN_IDS="$(echo ${line##*#} | tr -d ",")"
                        ;;
                *_NET_ACTIVE_WINDOW*)
                        _ACTWIN_ID="${line##*#}"
                        _ACTWIN_ID="${_ACTWIN_ID%%,*}"
                        ;;
                *_NET_CURRENT_DESKTOP*)
                        _CURR_WS="${line##* }"
                        ;;
                esac
        done
}

get_curr_win_props() {
        xprop -id "$1" _NET_WM_DESKTOP _NET_WM_WINDOW_TYPE WM_STATE |&
        while read -p line; do
                case "$line" in
                *_NET_WM_DESKTOP*)
                        _CURR_WIN_WS="${line##* }"
                        ;;
                *_NET_WM_WINDOW_TYPE*)
                        _CURR_WIN_TYPE="${line##* }"
                        ;;
                *state*)
                        _CURR_WIN_STATE="${line##* }"
                        ;;
                esac
        done
}

get_viswin_ids() {
        # Get visible window ids from current workspace (or set of
        # active groups/tags) and screen, excluding docks and panels
        actwin_id="$1"
        for win_id in $_WIN_IDS
        do
                read wo_x0 wo_y0 <<- EOT
			$(get_win_orig $win_id)
		EOT

                get_curr_win_props "$win_id"
                [ "$win_id" != "$actwin_id" ] &&
                (pgrep -x cwm >/dev/null || [ "$_CURR_WIN_WS" = "$_CURR_WS" ]) &&
                [[ "$_CURR_WIN_TYPE" != *DOCK* ]] && [[ "$_CURR_WIN_TYPE" != *DESKTOP* ]] &&
                [ "$_CURR_WIN_STATE" == Normal  ] &&
                [ $wo_x0 -ge $act_x0 ] && [ $wo_x0 -lt $(($act_x0 + $act_xdim)) ] &&
                [ $wo_y0 -ge $act_y0 ] && [ $wo_y0 -lt $(($act_y0 + $act_ydim)) ] &&
                        echo $win_id
        done
}

get_win_orig() {
        # Get window's origin coordinates
        #
        xwininfo -id ${1:-$_ACTWIN_ID} |
        grep "Absolute upper-left" |
        tail -n 2 |
        awk '{print $4}' |
        xargs
}

get_win_output_geom() {
        # Get geometry of the screen containing current window's origin
        #
        read w_x0 w_y0 <<- EOT
		$(get_win_orig ${1:-$_ACTWIN_ID})
	EOT
        for output_geom in \
            $(xrandr -q |
              awk '
                  /\<connected\>/ {for(i=1; i<=NF; i++) {
                                        g=match($i, /[0-9]+x[0-9]+\+[0-9]+\+[0-9]+/)
                                        if(g) print $i }
                  }
                  # RandR v1.0|1.1: Extend not supported
                  # (just report the output geometry with +0+0 origin)
                  /^\*/ {printf "%dx%d+0+0", $2, $4}
              ')
        do
                IFS="x+" read xdim ydim x0 y0 <<- EOT
			$(echo $output_geom)
		EOT
                if [ $x0 -le $w_x0 ] &&
                   [ $w_x0 -le $(($x0 + $xdim)) ] &&
                   [ $y0 -le $w_y0 ] &&
                   [ $w_y0 -le $(($y0 + $ydim)) ]
                then
                        echo $output_geom
                        break
                fi
        done
}

get_win_actarea() {
        # Get the active area of the screen
        # (i.e. geometry, excluded docks, panels, ...)
        #
        IFS="x+" read output_xdim output_ydim output_x0 output_y0 <<- EOT
		$(get_win_output_geom ${1:-$_ACTWIN_ID})
	EOT
        read work_x0 work_y0 work_xdim work_ydim DISCARD <<- EOT
		$(xprop -root _NET_WORKAREA |
		awk 'BEGIN{FS=" = "} {print $2}' |
		tr -d ",")
	EOT
        # This is the only practical assumption I can see: if there are
        # panels/docks, they are all on the "primary" monitor (i.e., the
        # one with (0,0) origin...)
        if [ $output_x0 -eq 0 ] && [ $output_y0 -eq 0 ]
        then
                [ $work_x0   -le $output_xdim ] && act_x0=$work_x0 || act_x0=$output_x0
                [ $work_xdim -le $output_xdim ] && act_xdim=$work_xdim || act_xdim=$output_xdim
                [ $work_y0   -le $output_ydim ] && act_y0=$work_y0 || act_y0=$output_y0
                [ $work_ydim -le $output_ydim ] && act_ydim=$work_ydim || act_ydim=$output_ydim
        else
                act_x0=$output_x0
                act_xdim=$output_xdim
                act_y0=$output_y0
                act_ydim=$output_ydim
        fi
        echo $act_x0 $act_y0 $act_xdim $act_ydim
}

get_win_frame() {
        # Get current window's frame extension)
        #
        f="$(xprop -id ${1:-$_ACTWIN_ID} _NET_FRAME_EXTENTS |
            awk 'BEGIN{FS=" = "} {print $2}' |
            tr -d ",")"

        # For non-EWMH, just return a sane default
        echo "${f:-2 2 20 2}"
}

tile() {
        # Tile specified window to top, bottom, left or right of the screen
        # or
        # tile visible windows horizontally or vertically
        #
        # Note: wmctrl will place windows *and* *frame* according to
        #       "-e" option (but the dimension does't consider the
        #       frame extension)
        #
        get_root_win_props
        tile_action=${1:-t}
        tile_gap=${2:-2}
        win_id=${3:-$_ACTWIN_ID}
        read act_x0 act_y0 act_xdim act_ydim <<- EOT
		$(get_win_actarea $win_id)
	EOT
        wmctrl -i -r $win_id -b remove,maximized_horz,maximized_vert
        read frame_l frame_r frame_t frame_b <<- EOT
		$(get_win_frame $win_id)
	EOT

        case $tile_action in
        t)
                win_x0=$act_x0
                win_y0=$act_y0
                win_xdim=$(($act_xdim - $frame_r - $frame_l - $tile_gap / 2))
                win_ydim=$(($act_ydim / 2 - $frame_t - $frame_b - $tile_gap / 2))
                wmctrl -i -r $win_id -e 0,$win_x0,$win_y0,$win_xdim,$win_ydim
                ;;
        b)
                win_x0=$act_x0
                win_y0=$(($act_y0 + $act_ydim / 2 + $tile_gap / 2))
                win_xdim=$(($act_xdim - $frame_r - $frame_l - $tile_gap / 2))
                win_ydim=$(($act_ydim / 2 - $frame_t - $frame_b - $tile_gap / 2))
                wmctrl -i -r $win_id -e 0,$win_x0,$win_y0,$win_xdim,$win_ydim
                ;;
        l)
                win_x0=$act_x0
                win_y0=$act_y0
                win_xdim=$(($act_xdim / 2 - $frame_r - $frame_l - $tile_gap / 2))
                win_ydim=$(($act_ydim - $frame_t - $frame_b - $tile_gap / 2))
                wmctrl -i -r $win_id -e 0,$win_x0,$win_y0,$win_xdim,$win_ydim
                ;;
        r)
                win_x0=$(($act_x0 + $act_xdim / 2 + $tile_gap / 2))
                win_y0=$act_y0
                win_xdim=$(($act_xdim / 2 - $frame_r - $frame_l - $tile_gap / 2))
                win_ydim=$(($act_ydim - $frame_t - $frame_b - $tile_gap / 2))
                wmctrl -i -r $win_id -e 0,$win_x0,$win_y0,$win_xdim,$win_ydim
                ;;
        tl)
                win_x0=$act_x0
                win_y0=$act_y0
                win_xdim=$(($act_xdim / 2 - $frame_r - $frame_l - $tile_gap / 2))
                win_ydim=$(($act_ydim / 2 - $frame_t - $frame_b - $tile_gap / 2))
                wmctrl -i -r $win_id -e 0,$win_x0,$win_y0,$win_xdim,$win_ydim
                ;;
        tr)
                win_x0=$(($act_x0 + $act_xdim / 2 + $tile_gap / 2))
                win_y0=$act_y0
                win_xdim=$(($act_xdim / 2 - $frame_r - $frame_l - $tile_gap / 2))
                win_ydim=$(($act_ydim / 2 - $frame_t - $frame_b - $tile_gap / 2))
                wmctrl -i -r $win_id -e 0,$win_x0,$win_y0,$win_xdim,$win_ydim
                ;;
        bl)
                win_x0=$act_x0
                win_y0=$(($act_y0 + $act_ydim / 2 + $tile_gap / 2))
                win_xdim=$(($act_xdim / 2 - $frame_r - $frame_l - $tile_gap / 2))
                win_ydim=$(($act_ydim / 2 - $frame_t - $frame_b - $tile_gap / 2))
                wmctrl -i -r $win_id -e 0,$win_x0,$win_y0,$win_xdim,$win_ydim
                ;;
        br)
                win_x0=$(($act_x0 + $act_xdim / 2 + $tile_gap / 2))
                win_y0=$(($act_y0 + $act_ydim / 2 + $tile_gap / 2))
                win_xdim=$(($act_xdim / 2 - $frame_r - $frame_l - $tile_gap / 2))
                win_ydim=$(($act_ydim / 2 - $frame_t - $frame_b - $tile_gap / 2))
                wmctrl -i -r $win_id -e 0,$win_x0,$win_y0,$win_xdim,$win_ydim
                ;;
        h)
                # Main window (note: recursively calling "tile t $tile_gap "" " is less efficient)
                win_x0=$act_x0
                win_y0=$act_y0
                win_xdim=$(($act_xdim - $frame_r - $frame_l - $tile_gap / 2))
                win_ydim=$(($act_ydim / 2 - $frame_t - $frame_b - $tile_gap / 2))
                wmctrl -i -r $win_id -e 0,$win_x0,$win_y0,$win_xdim,$win_ydim

                # Other windows
                _array viswin_ids $(get_viswin_ids $win_id)
                viswin_no=${#viswin_ids[@]}
                win_xdim=$((($act_xdim - \
                             $tile_gap * ($viswin_no - 1) - \
                             ($frame_l + $frame_r) * $viswin_no) / $viswin_no))
                win_y0=$(($act_y0 + $act_ydim / 2 + $tile_gap / 2))
                win_ydim=$(($act_ydim / 2 - $frame_t - $frame_b - $tile_gap / 2))
                win_cnt=0
                for viswin_id in ${viswin_ids[@]}
                do
                        win_cnt=$(($win_cnt + 1))
                        win_x0=$(($act_x0 + ($win_xdim + $frame_l + $frame_r + $tile_gap) * ($win_cnt - 1)))
                        wmctrl -i -r $viswin_id -b remove,maximized_horz,maximized_vert
                        wmctrl -i -r $viswin_id -e 0,$win_x0,$win_y0,$win_xdim,$win_ydim
                done
                ;;
        v)
                # Main window (note: recursively calling "tile l $tile_gap "" " is less efficient)
                win_x0=$act_x0
                win_y0=$act_y0
                win_xdim=$(($act_xdim / 2 - $frame_r - $frame_l - $tile_gap / 2))
                win_ydim=$(($act_ydim - $frame_t - $frame_b - $tile_gap / 2))
                wmctrl -i -r $win_id -e 0,$win_x0,$win_y0,$win_xdim,$win_ydim

                # Other windows
                _array viswin_ids $(get_viswin_ids $win_id)
                viswin_no=${#viswin_ids[@]}
                win_x0=$(($act_x0 + $act_xdim / 2 + $tile_gap / 2))
                win_xdim=$(($act_xdim / 2 - $frame_l - $frame_r - $tile_gap / 2))
                win_ydim=$((($act_ydim - \
                                   $tile_gap * ($viswin_no - 1) - \
                                   ($frame_t + $frame_b) * $viswin_no) / $viswin_no))
                win_cnt=0
                for viswin_id in ${viswin_ids[@]}
                do
                        win_cnt=$(($win_cnt + 1))
                        win_y0=$(($act_y0 + ($win_ydim + $frame_t + $frame_b + $tile_gap) * ($win_cnt - 1)))
                        wmctrl -i -r $viswin_id -b remove,maximized_horz,maximized_vert
                        wmctrl -i -r $viswin_id -e 0,$win_x0,$win_y0,$win_xdim,$win_ydim
                done
                ;;
        *)
                _usage
                exit 1
                ;;
        esac
}

move2ws() {
        # Move window to workspace (and optionally activate it)
        #
        get_root_win_props
        ws=${1:-$_CURR_WS}
        if env test "$ws" -lt $(xprop -root _NET_NUMBER_OF_DESKTOPS |
                                awk 'BEGIN{FS=" = "} {print $2}') 2>/dev/null
        then
                activate=${2:-0}
                win_id="${3:-$_ACTWIN_ID}"
                wmctrl -i -r $win_id -t $ws
                [ "$activate" = 1 ] && wmctrl -i -a $win_id
        else
                _usage
                exit 1
        fi
}

winaction() {
        get_root_win_props
        action="${1:-max}"
        win_id="${2:-$_ACTWIN_ID}"
        case "$action" in
        *max*)
                # Toggle maximized state of window (and optionally raise it)
                #
                if [ "${action#force}" != "$action" ]; then
                        wmctrl -i -r "$win_id" -b add,maximized_horz,maximized_vert
                else
                        wmctrl -i -r "$win_id" -b toggle,maximized_horz,maximized_vert
                fi
                [ "${action%raise}" != "$action" ] && wmctrl -i -a "$win_id"
                ;;
        kill)
                # Kill a client by its X resource
                #
                xkill -id "$win_id"
                ;;
        *)
                _usage
                exit 1
                ;;
        esac
}

getwinid() {
        if [ -n "$1" ]; then
                for win_id in $_WIN_IDS; do
                        if xprop -id $win_id WM_NAME WM_CLASS |
                           grep "$1" >/dev/null 2>&1
                        then
                                echo $win_id
                                break
                        fi
                done
        else
                _usage
                exit 1
        fi
}

# main() {
        case "${0##*/}" in
        wmprocs)
                if [ $# -eq 0 ]; then
                        _usage
                        exit 1
                else
                        command="$1"
                        shift
                fi
                ;;
        tile | move2ws | winaction | getwinid)
                command="${0##*/}"
                ;;
        *)
                _usage
                exit 1
                ;;
        esac

        # Optional argument parsing
        while [ $# -gt 0 ]; do
                case "$1" in
                -g)
                        if [ "$command" != tile ] || [ $# -lt 2 ]; then
                                _usage
                                exit 1
                        else
                                shift
                                tile_gap="$1"
                        fi
                        ;;
                -a)
                        if [ "$command" != move2ws ]; then
                                _usage
                                exit 1
                        else
                                activate_ws=1
                        fi
                        ;;
                -w)
                        if [ $# -lt 2 ]; then
                                _usage
                                exit 1
                        else
                                shift
                                win_id="$1"
                        fi
                        ;;
                *)
                        action=$1
                        ;;
                esac
                shift
        done

        case "$command" in
        mk_links)
                ln -s $0 $(dirname $0)/tile
                ln -s $0 $(dirname $0)/move2ws
                ln -s $0 $(dirname $0)/winaction
                ln -s $0 $(dirname $0)/getwinid
                ;;
        rm_links)
                rm -f $(dirname $0)/tile
                rm -f $(dirname $0)/move2ws
                rm -f $(dirname $0)/winaction
                rm -f $(dirname $0)/getwinid
                ;;
        tile)
                tile "${action:-""}" "${tile_gap:-""}" "${win_id:-""}"
                ;;
        move2ws)
                move2ws "${action:-""}" "${activate_ws:-""}" "${win_id:-""}"
                ;;
        winaction)
                winaction "${action:-""}" "${win_id:-""}"
                ;;
        getwinid)
                getwinid "${action:-""}"
                ;;
        help)
                _help | ${PAGER:-less}
                ;;
        *)
                _usage
                exit 1
                ;;
        esac
        exit 0
# }
