#!/bin/sh

# ----------------------------------------------------------------------
#  $Id$
#
#  X display layout management with dual monitor configurations
# ----------------------------------------------------------------------

# No output msgs, please
exec >/dev/null 2>&1

# Clean up statusbar area
pkill -x dzen2
pkill -x space_dapp

# Turn off desktop manager
pcmanfm --desktop-off

# Change display layout
xrandr $@

# Restart statusbar
(sleep 2; statusbar) &
(sleep 3; space_dapp) &

# Restart window manager
if pgrep -x fluxbox; then
        fbsetroot -gradient Vertical -from rgb:07/36/42 -to rgb:58/6E/75
        fluxbox-remote restart
elif pgrep -x openbox; then
        xsetroot -solid rgb:58/6E/75
        #openbox --restart
elif pgrep -x fvwm2; then
        xsetroot -solid rgb:58/6E/75
        FvwmCommand Restart
fi

# Wallpaper setting
[ -x ~/.fehbg ] && ~/.fehbg

# Launch desktop manager
pcmanfm --desktop &
