#!/bin/sh

# ----------------------------------------------------------------------
#  $Id$
#
#  Restart window manager (typically after a screen resolution change)
# ----------------------------------------------------------------------

# No output msgs, please
exec >/dev/null 2>&1

# Clean up
if pgrep -x fluxbox; then
        pkill -x bbpager
        pkill -x space_dapp
        #pcmanfm --desktop-off
fi

# Restart window manager
if pgrep -x fluxbox; then
        sleep 2
        fluxbox-remote Restart
        sleep 2
fi
nitrogen --restore

# Relaunch startup programs
if pgrep -x fluxbox; then
        space_dapp $((($(screen-width) - 1))) 17 &
        dbar -xs "${xs:-1}" &
        sleep 1; bbpager &
        #pcmanfm --desktop &
fi

