#!/bin/sh

# ----------------------------------------------------------------------
#  $Id$
#
#  X display layout management with dual monitor configurations
# ----------------------------------------------------------------------

# No output msgs, please
exec >/dev/null 2>&1

# Clean up statusbar
if pkill -x bbpager; then
        restart_bbpager=1
fi
if pkill -x dzen2; then
        restart_headup=1
fi
if pgrep -x pcmanfm; then
        pcmanfm --desktop-off
        restart_pcmanfm_desktop=1
fi

# Change display layout
xrandr $@

# Restart window manager
if pgrep -x dwm; then
        [ -x ~/.fehbg ] && ~/.fehbg
elif pgrep -x fluxbox; then
        fluxbox-remote Restart
        fbsetbg -l
elif pgrep -x openbox; then
        xsetroot -solid rgb:58/6E/75
        openbox --restart
        [ -x ~/.fehbg ] && ~/.fehbg
elif pgrep -x fvwm2; then
        xsetroot -solid rgb:58/6E/75
        FvwmCommand Restart
        [ -x ~/.fehbg ] && ~/.fehbg
fi

[ $restart_bbpager -eq 1 ] && bbpager &
[ $restart_headup  -eq 1 ] && headup
[ $restart_pcmanfm_desktop  -eq 1 ] && pcmanfm --desktop &
