#!/bin/sh

# ----------------------------------------------------------------------
#  $Id$
#
#  Restore wallpaper (typically after a screen resolution change)
# ----------------------------------------------------------------------

nitrogen --restore

