#!/bin/sh

# ----------------------------------------------------------------------
#  $Id$
#
#  Restart problematic apps in Xfce
# ----------------------------------------------------------------------

# Statusbar
pkill dzen2
dbar | dzen2 -title-name dbar \
             -bg "#eee8d5" -fg "#073642" -fn "DejaVu Sans Mono:size=9" \
             -p -e "" -expand left -dock -xs 1 &
