#!/bin/sh

# ----------------------------------------------------------------------
#  $Id$
#
#  Reset X screen when SIGUSR1 is received (typically before suspend to
#  RAM/disk operations)
# ----------------------------------------------------------------------

# Kill daemon on exit
trap "LOOP=0; rm ~/.xscreen-reset.pid" HUP INT QUIT ABRT TERM

# Check if daemon is already running
DAEMON_PID=$(cat ~/.xscreen-reset.pid 2> /dev/null)
if DAEMON_STATE=$(ps -o stat="" -p $DAEMON_PID 2> /dev/null); then
        case "$DAEMON_STATE" in
        I*|R*|S*)
                echo "Daemon already running with pid $DAEMON_PID"
                exit 1
                ;;
        *)
                echo "Killing old stopped/dead daemon with pid $DAEMON_PID"
                kill -KILL $DAEMON_PID
                ;;
        esac
fi
echo "Launching daemon with pid $$"
echo $$ > ~/.xscreen-reset.pid

# Reset X screen to LVDS1 (auto) and lock it when SIGUSR1 is received
trap 'screen-reset' USR1

# No output msgs, please
exec >/dev/null 2>&1

# Main function
screen-reset () {
	# Force LVDS-only display layout
	wmrestart --display $DISPLAY --output LVDS1 --auto --output VGA1 --off --output DVI1 --off

	# Lock the screen
        xscreensaver-command -lock
}

# Daemonize
LOOP=1
while [ "${LOOP}" == 1 ]; do
    sleep 1
done
