#!/bin/sh

# ----------------------------------------------------------------------
#  $Id$
#
#  Typically used before suspend to RAM/disk operations:
#  - reset the screen (forcing LVDS only) and lock it;
#  - reset keyboard layout to "it".
# ----------------------------------------------------------------------

# No output msgs, please
exec >/dev/null 2>&1

# Restart/enable xautolock
if ! pgrep -u $USER xautolock; then
        xautolock -detectsleep -time 10 -locker slock &
else
        xautolock -enable
fi

# Reset keyboard layout
setxkbmap it

# Lock the screen
xautolock -locknow

# Force LVDS-only display layout
dmenu-xrandr Off
