#!/bin/sh

# ----------------------------------------------------------------------
#  $Id$
#
#  Typically used before suspend to RAM/disk operations:
#  - reset the screen (forcing LVDS only) and lock it;
#  - reset keyboard layout to "it".
# ----------------------------------------------------------------------

# No output msgs, please
exec >/dev/null 2>&1

# Restart xautolock
pkill -u $USER xautolock
xautolock -detectsleep -time 10 -locker lock-screen &

# Reset keyboard layout
setxkbmap -layout us

# Lock the screen
xautolock -locknow

# Force LVDS-only display layout
dmenu-xrandr LVDS

exit 0
