#!/bin/sh

# ----------------------------------------------------------------------
#  $Id$
#
#  Plays Youtube (or similar) video whom url is into the clipboard
#  (First release: 20140627)
#  Dependencies: youtube-dl, smplayer
# ----------------------------------------------------------------------

URL=$1

# curl supports htpps
smplayer $(youtube-dl -f best -g $URL)

#cat /dev/null | xclip
