#!/bin/sh

# ----------------------------------------------------------------------
#  $Id$
#
#  Plays Youtube (or similar) video whom url is into the clipboard
#  (First release: 20140627)
#  Dependencies: youtube-dl, xclip, mplayer
# ----------------------------------------------------------------------

URL=$(xclip -o)

# curl supports htpps
curl $(youtube-dl -f best -g $URL) | mplayer -cache 4096 -cache-min 5 -

cat /dev/null | xclip
