#!/bin/sh

# File:     yt-mplayer
# Purpose:  play yt (or similar) video whom url is into the clipboard
# Author:   A. DE LAURENZIS
# Date:     20140627

URL=$(xclip -o)

# curl supports htpps
curl $(youtube-dl -f best -g $URL) | mplayer -cache 4096 -cache-min 5 -

cat /dev/null | xclip
