#!/bin/sh

# ----------------------------------------------------------------------
#  $Id$
#
#  Date/time module for dbar
# ----------------------------------------------------------------------


# Print time and wait for next HH:MM...
echo "$(date "+%a %d %b, %H:%M");"
sleep $((60 - $(date "+%S")))

#...and now, reprint time one time a minute
while : ; do
        echo "$(date "+%a %d %b, %H:%M");"
        sleep 60
done
