#!/bin/sh

# ----------------------------------------------------------------------
#  $Id$
#
#  CPU and memory usage module for dbar
# ----------------------------------------------------------------------

vmstat -w 2 |
awk '
        /^[[:space:]]*[0-9]+/ {
                avm_exp = index("KMG", substr($3, length($3)));
                avm_mnt = substr($3, 1, length($3) - 1);
                avm = avm_mnt * 10^(avm_exp * 3);
                fre_exp = index("KMG", substr($4, length($4)));
                fre_mnt = substr($4, 1, length($4) - 1);
                fre = fre_mnt * 10^(fre_exp * 3);
                printf("[P:%3d%%] [M:%3d%%]\n", 100 - $NF, 100 * avm / (avm + fre));
        }
'
