#!/bin/sh

#DISK_ICON="<img>/home/just22/.local/share/icons/sm4tik-icon-pack/xbm/diskette.xbm</img>"
DISK_ICON="<img>/home/just22/.local/share/icons/sm4tik-icon-pack/png-transparent_bg/diskette.png</img>"

IO_ACTIVITY=$(iostat -c2 -d sd0 |
                tail -n1 |
                awk '{printf "%.2f MB/s", $3}')
printf "%s<txt> %-10s</txt><tool></tool>" "$DISK_ICON" "$IO_ACTIVITY"
