#!/bin/sh

#NET_DOWN_ICON="<img>/home/just22/.local/share/icons/sm4tik-icon-pack/xbm/net_down_02.xbm</img>"
NET_DOWN_ICON="<img>/home/just22/.local/share/icons/sm4tik-icon-pack/png-transparent_bg/net_down_02.png</img>"

NET_DOWN_ACTIVITY=$(ifstat -n -i trunk0 0.25 2 |
        tail -n1 |
        awk '{printf "%.2f MB/s", $1/1000}')
printf "%s<txt> %-10s</txt><tool></tool>" \
        "$NET_DOWN_ICON" \
        "$NET_DOWN_ACTIVITY"
