#!/bin/sh

VOL_LEVEL=$(mixerctl -n outputs.master |
                cut -d"," -f1 |
                awk '{printf "%d", $1/255*100}')
MUTE=$(mixerctl -n outputs.master.mute)

if [ "$VOL_LEVEL" -eq 0 -o "$MUTE" == "on" ]; then
        VOL_ICON="<img>/home/just22/.local/share/icons/stlarch_icons/png-transparent_bg/vol3.png</img>"
elif [ "$VOL_LEVEL" -gt 50 ]; then
        VOL_ICON="<img>/home/just22/.local/share/icons/stlarch_icons/png-transparent_bg/vol1.png</img>"
else
        VOL_ICON="<img>/home/just22/.local/share/icons/stlarch_icons/png-transparent_bg/vol2.png</img>"
fi

printf "%s<txt> %-4s</txt><tool></tool>" "$VOL_ICON" "$VOL_LEVEL%"
